[package]
name = "git-mirrorbot"
edition = "2021"
version = "0.0.0"

[dependencies]
git2 = "0.14.2"
env_logger = "0.9"
log = "0.4.14"
toml = "0.5.8"
serde = "1.0"
serde_derive = "1.0"
anyhow = "1.0.51"
indicatif = "0.16.2"
reqwest = { version = "0.11", features = ["blocking", "json"] }
