name: Release

on:
  push:
    branches: [ main ]
    tags: [ 'v*.*.*' ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Build release binary
        run: cargo build --release --verbose

      - name: Run tests
        run: cargo test --release --verbose # Run tests on release build

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: git-mirrorbot-binary
          path: target/release/git-mirrorbot # Adjust binary name if needed

  upload_dev_binary:
    name: Upload Nightly Binary Artifact # Changed name for clarity
    needs: build
    if: github.ref == 'refs/heads/main' && github.event_name == 'push' # Only on direct pushes to main
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: git-mirrorbot-binary

      - name: Make binary executable
        run: chmod +x git-mirrorbot

      - name: Upload release asset
        uses: softprops/action-gh-release@v2
        with:
          files: git-mirrorbot
          tag_name: nightly

  upload_binary:
    name: Upload Release Binary
    needs: build # Depends on the build job
    if: startsWith(github.ref, 'refs/tags/v') # Only run on tag pushes like v1.0.0
    runs-on: ubuntu-latest
    permissions:
      contents: write # Needed to create releases and upload assets
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: git-mirrorbot-binary

      - name: Make binary executable
        run: chmod +x git-mirrorbot

      - name: Upload release asset
        uses: softprops/action-gh-release@v2
        with:
          files: git-mirrorbot
