name: Release

on:
  push:
    branches: [ main ]
    tags: [ 'v*.*.*' ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Build release binary
        run: cargo build --release --verbose

      - name: Run tests
        run: cargo test --release --verbose

      - name: Install cargo-deb
        run: cargo install --force cargo-deb

      - name: Build deb package
        run: cargo deb

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: git-mirrorbot-binary
          path: |
            target/release/git-mirrorbot
            target/debian/*.deb

  upload_dev_binary:
    name: Upload Nightly Binary Artifact
    needs: build
    if: github.ref == 'refs/heads/main' && github.event_name == 'push' # Only on direct pushes to main
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: git-mirrorbot-binary

      - name: Make binary executable
        run: chmod +x git-mirrorbot

      - name: Upload release asset
        uses: softprops/action-gh-release@v2
        with:
          files: |
            git-mirrorbot
            target/debian/*.deb
          tag_name: nightly
